gui:
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  border: rounded
  selectedLineBgColor:
    - underline
  selectedRangeBgColor:
    - underline
os:
  edit: 'nvim {{filename}}'
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
